EndPoint/Controllers/OppratorsController.cs
using Domain.Core.App.Requests.AppServices;
using Domain.Core.App.Users.Enums;
using Infra.DataBase;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace EndPoint.Controllers
{
    public class OppratorsController : Controller
    {
        private readonly IRequestAppService requestAppService;
        public OppratorsController(IRequestAppService requestApp)
        {
            requestAppService = requestApp;
        }
        public IActionResult Index()
        {
            if (OnlineUser.CurrentUser != null && OnlineUser.CurrentUser.Role == UserRoleEnum.admin)
            {
            var requests = requestAppService.GetPendingRequests();
            return View(requests);
            }
            return Redirect("/user");

        }
        [HttpGet]
        public IActionResult Approve(int id)
        {
            try
            {
                TempData["Message"] = requestAppService.ApproveRequests(id);
                TempData["AlertType"] = "success";
                return RedirectToAction("Index");
            }

            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["AlertType"] = "danger";
                return View("Index");
            }
        }

        public IActionResult Disapprove(int id)
        {
            
           
            try
            {
                TempData["Message"] = requestAppService.Dissapprove(id);
                TempData["AlertType"] = "success";
                return RedirectToAction("Index");
            }

            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["AlertType"] = "danger";
                return View("Index");
            }
        }
        
            
    }
}

EndPoint/Controllers/RequestController.cs
using Domain.Core.App.Cars.AppServices;
using Domain.Core.App.RequestLogs.AppServices;
using Domain.Core.App.Requests.AppServices;
using Domain.Core.App.Requests.Entity;
using Domain.Core.App.Requests.Services;
using Domain.Core.App.UserCars.AppServices;
using Infra.DataBase;
using Microsoft.AspNetCore.Mvc;

namespace EndPoint.Controllers
{
    public class RequestController : Controller
    {
        private readonly IUserCarAppService carAppService;
        private readonly ICarAppService _carAppService;
        private readonly IRequestAppService requestAppService;
        private readonly IConfiguration Configuration;
        private readonly IRequestLogAppService requestLogAppService;
        private readonly IUserCarAppService userCarAppServiceX;

        public RequestController(IUserCarAppService userCarAppService, ICarAppService carApp, IRequestAppService requestApp,IRequestLogAppService requestLog, IUserCarAppService userCarAppService1)
        {
            carAppService = userCarAppService;
            _carAppService = carApp;
            requestAppService = requestApp;
            userCarAppServiceX = userCarAppService1;
            requestLogAppService = requestLog;
        }
        public IActionResult Index()
        {
            if (OnlineUser.CurrentUser != null)
            {

                return RedirectToAction("LoggedInRequest");
            }

            var cars = _carAppService.GetAllCars();
            return View(cars);
        }
        [HttpPost]
        public IActionResult SendRequest(string Plate, int Car, string nationalcode, string phoneNumber, string Address)
        {
            try
            {
                var req = new Request() { Address = Address, Plate = Plate, CarId = Car, NationalCode = nationalcode, PhoneNumber = phoneNumber };
                requestAppService.AddRequest(req);
                return Redirect("/Home");

            }

            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["AlertType"] = "danger";
                return RedirectToAction("Index");
            }
        }

        public IActionResult LoggedInRequest()
        {
            var cars = carAppService.GetUserCars(OnlineUser.CurrentUser);
            return View(cars);
        }
        [HttpPost]
        public IActionResult LoggedInRequest(int Car)
        {
            try
            {
                var car = userCarAppServiceX.GetUserCarById(Car);
                var req = new Request() { Address = OnlineUser.CurrentUser.Address, Plate = car.Plate, CarId = car.CarId, NationalCode = OnlineUser.CurrentUser.NationalCode, PhoneNumber = OnlineUser.CurrentUser.PhoneNumber };
                requestAppService.AddRequest(req); 
                return Redirect("/Home");
            }

            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["AlertType"] = "danger";
                return RedirectToAction("LoggedInRequest");
            }
        }
        public IActionResult PastRequests()
        {
            if (OnlineUser.CurrentUser == null)
            {
                return RedirectToAction("Index", "User");
            }
            var cars = requestAppService.GetPastRequests(OnlineUser.CurrentUser);
            return View(cars);
        }
        public IActionResult DisapprovedRequests()
        {
            if (OnlineUser.CurrentUser == null)
            {
                return RedirectToAction("Index", "User");
            }
            var cars = requestLogAppService.GetAllDisapprovedRequests(OnlineUser.CurrentUser);
            return View(cars);
        }

    }
}

EndPoint/Controllers/UserCarsController.cs
using AppService.App.Requests;
using Domain.Core.App.Cars.AppServices;
using Domain.Core.App.UserCars.AppServices;
using Domain.Core.App.Users.AppServices;
using Infra.DataBase;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Net;

namespace EndPoint.Controllers
{
    public class UserCarsController : Controller
    {
        private readonly ICarAppService carAppService;
        private readonly IUserCarAppService userCarAppService;
        public UserCarsController(ICarAppService carApp, IUserCarAppService userCarApp)
        {
            carAppService = carApp;
            userCarAppService = userCarApp;
        }
        public IActionResult Index()
        {
            if (OnlineUser.CurrentUser == null)
            {
                return RedirectToAction("Index", "User");
            }
            var cars= carAppService.GetAllCars();
            return View(cars);
        }
        [HttpPost]
        public IActionResult AddCar(string Plate, int Car)
        {
            
           
            
            try
            {
                var car = carAppService.GetCarsById(Car);
                userCarAppService.AddUserCar(OnlineUser.CurrentUser, Plate, car);
                return RedirectToAction("Index");

            }

            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["AlertType"] = "danger";
                return RedirectToAction("Index");
            }
        }

    }
}

EndPoint/Controllers/UserController.cs
using Azure.Core.Pipeline;
using Domain.Core.App.Opperators.Entity;
using Domain.Core.App.Users.AppServices;
using Domain.Core.App.Users.Entity;
using Domain.Core.App.Users.Enums;
using Infra.DataBase;
using Microsoft.AspNetCore.Mvc;

namespace EndPoint.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserAppService _userAppService;
        public UserController(IUserAppService userAppService)
        {
            _userAppService = userAppService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string NationalCode, string password)
        {
            try
            {
                OnlineUser.CurrentUser = _userAppService.Login(NationalCode, password);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["AlertType"] = "danger";
                return View("Index");
            }
            
            return View("Index");
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(string nationalcode, string password, string phoneNumber, string Address)
        {
            try
            {
                TempData["Message"] = _userAppService.Register(nationalcode, password, phoneNumber, Address);
                TempData["AlertType"] = "success";
                return View();
            }

            catch (Exception ex) 
            {
                TempData["Message"] = ex.Message;
                TempData["AlertType"] = "danger";
                return View("Index");
            }
        }

        public IActionResult LogOut()
        {
            OnlineUser.CurrentUser=null;
            return RedirectToAction("Index");
        }
    }
}

EndPoint/Views/Shared/_Layout.cshtml
@using Infra.DataBase;
@using Domain.Core.App.Users.Enums;

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cw__17</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cw__17.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cw__17</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Send request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="PastRequests">Past Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="DisapprovedRequests">Disapproved Requests</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserCars" asp-action="Index">Add Cars</a>
                        </li>

                        @{
                            if (OnlineUser.CurrentUser!=null && OnlineUser.CurrentUser.Role == UserRoleEnum.admin)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark " asp-area=""  asp-controller="Opprators" asp-action="Index">Pending Requests</a>
                                </li>
                            }
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="User" asp-action="Index">Login</a>
                        </li>



                        <li class="nav-item">
                            <a asp-action="LogOut" asp-controller="User" class="btn btn-danger">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted fixed-bottom">
        <div class="container">
            &copy; 2024 - cw__17 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>